/* DEFAULTS DON'T CHANGE THESE HERE */
/* OVERRIDE AT BOTTOM oF FILE */

/* SIMULATION PV3VIEWER FINDMAX */
#define SIMULATION

/* KOVASZNAY TEST CYLINDER SPHERE FREESTREAM CONVDIFF */
/* UNSTEADY_DROP DROP TWOLAYER TWOLAYERNOINERTIA WAVE */
/* THREELAYER TAYLOR MOVING_TAYLOR ACCELERATING SOURCETERM*/
/* BOUNDARY_LAYER TWOSPHERE */
#define COLUMN

/* CIRCLE SIN COS NACA */
#define CIRCLE

/* 1 2 3 */
#define NV 3

/* BACKDIFF DIRK */
#define DIRK
#define TMSCHEME 4

#ifdef DIRK
#define DIRKSOLVES 3
#if (TMSCHEME == 3)
/* 3 STAGE SDIRK */
#define TMSTORE TMSCHEME
#define TMADAPT 1
#else
/* 4-STAGE ESDIRK */
#define TMSTORE TMSCHEME
#define TMADAPT 2
#endif
#endif
#ifdef BACKDIFF
/* 1 2 3 FOR BACKWARDS DIFFERENCES */
#if (TMSCHEME == 1)
#define TMSTORE 1
#else
#define TMSTORE TMSCHEME-1
#endif
#define TMADAPT TMSTORE
#endif

/* CONSERV  NONCONSERV */
#define CONSERV

/* AXISYMMETRIC  NO_AXISYMMETRIC */
#define NO_AXISYMMETRIC

/* INERTIALESS NO_INERTIALESS */
#define NO_INERTIALESS

/* TIMEACCURATE NO_TIMEACCURATE */
#define NO_TIMEACCURATE  

/* OLDRECONNECT NEWRECONNECT */
#define OLDRECONNECT 

/* TWO_LEVEL NO_TWO_LEVEL */
#define NO_TWO_LEVEL

/* NO_SOLVECOARSE NO_SOLVECOARSE */
#define NO_SOLVECOARSE 5

/* DEFORM  NO_DEFORM UNCOUPLED_DEFORMATION */
#define DEFORM

/* FOURTH NO_FOURTH */
#define NO_FOURTH

/* GEOMETRIC NO_GEOMETRIC */
#define GEOMETRIC

/* DEBUG NO_DEBUG */
#define NO_DEBUG 

/* ENERGY NO_ENERGY */
#define NO_ENERGY

/* BODY NO_BODY */
#define NO_BODY

/* PARAMETERLOOP NO_PARAMETERLOOP */
#define NO_PARAMETERLOOP

/* CONVERGENCE TOLERANCE */
#define CVGTOLREL 1.0e-12
#define CVGTOLABS 1.0e-12

#ifdef CIRCLE
#define RADIUS 0.5;
#define CENTERX 0.0;
#define CENTERY 0.0;
#endif

/* AUTOMATIC SWITCHES FOR PARTICULAR CASES */
#ifdef SPHERE
#undef DEFORM
#define NO_DEFORM
#undef NO_AXISYMMETRIC
#define AXISYMMETRIC
#endif

#ifdef TEST
#undef DEFORM
#define NO_DEFORM
#endif

#ifdef CYLINDER
#undef DEFORM
#define NO_DEFORM
#endif

#ifdef BOUNDARY_LAYER
#undef DEFORM
#define NO_DEFORM
#endif

#ifdef UNSTEADY_DROP
#undef NO_AXISYMMETRIC
#define AXISYMMETRIC
#undef NO_ENERGY
#define ENERGY
#endif

#ifdef DROP
#undef NO_PARAMETERLOOP
#define PARAMETERLOOP
#undef NO_AXISYMMETRIC
#define AXISYMMETRIC
#undef NO_ENERGY
#define ENERGY
#endif

#ifdef TWOLAYER
#undef CIRCLE
#define SIN
#define LAYER 2
#undef NO_BODY
#define BODY
#endif

#ifdef TWOLAYERNOINERTIA
#define TWOLAYER
#define LAYER 2
#define INERTIALESS
#undef CIRCLE
#define SIN
#undef NO_BODY
#define BODY
#endif

#ifdef THREELAYER
#undef NO_INERTIALESS
#define INERTIALESS
#undef CIRCLE
#define SIN
#define LAYER 3
#undef NO_BODY
#define BODY
#endif

#ifdef CONVDIFF
#define NV 1
#define CASE 0
#if (CASE == 2)
#undef NO_TIMEACCURATE
#define TIMEACCURATE
#endif
#undef DEFORM
#define NO_DEFORM
#endif

#ifdef WAVE
#undef CIRCLE
#define FREESTREAM
#endif

#ifdef FREESTREAM
#define ANALYTIC
#define ALIGNSQUARE
#undef DEFORM
#define NO_DEFORM
#endif

#ifdef SHEAR
#undef CIRCLE
#define WAVE
#undef DEFORM
#define NO_DEFORM
#endif

#ifdef TAYLOR
#undef DEFORM
#define NO_DEFORM
#define ANALYTIC
#define ALIGNSQUARE
#endif

#ifdef MOVING_TAYLOR
#define TAYLOR
#undef DEFORM
#define UNCOUPLED_DEFORMATION
#define ANALYTIC
#define ALIGNSQUARE
#endif

#ifdef ACCELERATING
#undef DEFORM
#define NO_DEFORM
#define ANALYTIC
#define ALIGNSQUARE
#endif

#ifdef KOVASZNAY
#define OUTF_STRESS
#define ANALYTIC
#define ALIGNSQUARE
#undef DEFORM
#define NO_DEFORM
#endif

#ifdef SOURCETERM
#define ANALYTIC
#define ALIGNSQUARE
#endif

#ifdef NOZZLE
#undef DEFORM
#define NO_DEFORM
#undef NO_AXISYMMETRIC
#define AXISYMMETRIC
#undef CIRCLE
#define VSIN
#endif

#ifdef TWOSPHERE
#undef NO_BODY
#define BODY
#undef NO_AXISYMMETRIC
#define AXISYMMETRIC
#endif

#ifdef COLUMN
#undef NO_BODY
#define BODY
#undef DEFORM
#define NO_DEFORM
#define NO_FRICTION
#undef CIRCLE
#define MOVING_WALL
#endif

