/* DEFAULTS DON'T CHANGE THESE HERE */
/* OVERRIDE AT BOTTOM oF FILE */

/* SIMULATION PV3VIEWER FINDMAX */
#define SIMULATION 

/* KOVASZNAY TEST CYLINDER SPHERE FREESTREAM CONVDIFF */
/* UNSTEADY_DROP DROP TWOLAYER TWOLAYERNOINERTIA WAVE */
/* THREELAYER */
#define DROP

/* CIRCLE SIN COS NACA */
#define CIRCLE

/* 1 2 3 */
#define NV 3

/* BACKDIFF DIRK */
#define BACKDIFF
#ifdef DIRK
#define TMSCHEME 3
#define TMSTORE TMSCHEME
#define TMADAPT 1
#endif
#ifdef BACKDIFF
/* 1 2 3 FOR BACKWARDS DIFFERENCES */
#define TMSCHEME 2
#if (TMSCHEME == 1)
#define TMSTORE 1
#else
#define TMSTORE TMSCHEME-1
#endif
#define TMADAPT TMSTORE
#endif

/* CONSERV  NONCONSERV */
#define CONSERV

/* AXISYMMETRIC  NO_AXISYMMETRIC */
#define NO_AXISYMMETRIC

/* INERTIALESS NO_INERTIALESS */
#define NO_INERTIALESS

/* TIMEACCURATE NO_TIMEACCURATE */
#define NO_TIMEACCURATE  

/* OLDRECONNECT NEWRECONNECT */
#define OLDRECONNECT 

/* TWO_LEVEL NO_TWO_LEVEL */
#define NO_TWO_LEVEL

/* SOLVECOARSE NO_SOLVECOARSE */
#define SOLVECOARSE 5

/* DEFORM  NO_DEFORM */
#define DEFORM

/* FOURTH NO_FOURTH */
#define NO_FOURTH

/* GEOMETRIC NO_GEOMETRIC */
#define GEOMETRIC

/* DEBUG NO_DEBUG */
#define NO_DEBUG 

/* ENERGY NO_ENERGY */
#define NO_ENERGY

/* PARAMETERLOOP NO_PARAMETERLOOP */
#define NO_PARAMETERLOOP

/* AUTOMATIC SWITCHES FOR PARTICULAR CASES */
#ifdef CIRCLE
#define RADIUS 0.5;
#define CENTERX 0.0;
#define CENTERY 0.0;
#endif

#if (defined(SPHERE) || defined(KOVASZNAY) || defined(CYLINDER) || defined(CONVDIFF) || defined(TEST) || defined(FREESTREAM))
#undef DEFORM
#define NO_DEFORM
#endif

#if (defined(SPHERE) || defined(DROP) || defined(UNSTEADY_DROP))
#undef NO_AXISYMMETRIC
#define AXISYMMETRIC
#endif

#if (defined(DROP) || defined(UNSTEADY_DROP))
#undef NO_ENERGY
#define ENERGY
#endif

#ifdef DROP
#undef NO_PARAMETERLOOP
#define PARAMETERLOOP
#endif

#ifdef TWOLAYER
#undef CIRCLE
#define SIN
#define LAYER 2
#endif

#ifdef TWOLAYERNOINERTIA
#define TWOLAYER
#define LAYER 2
#define INERTIALESS
#undef CIRCLE
#define SIN
#endif

#ifdef THREELAYER
#undef NO_INERTIALESS
#define INERTIALESS
#undef CIRCLE
#define SIN
#define LAYER 3
#endif

#ifdef CONVDIFF
#define NV 1
#define CASE 0
#if (CASE == 2)
#undef NO_TIMEACCURATE
#define TIMEACCURATE
#endif
#endif

#ifdef WAVE
#undef CIRCLE
#undef DEFORM
#define NO_DEFORM
#define FREESTREAM
#endif

#ifdef SHEAR
#undef CIRCLE
#define WAVE
#undef DEFORM
#define NO_DEFORM
#endif

