/*
 *  myblas.h
 *  planar++
 *
 *  Created by helenbrk on Tue Oct 09 2001.
 *  Copyright (c) 2001 __CompanyName__. All rights reserved.
 *
 */

#define f2cFortran
#include<cfortran.h>

extern "C" void DPBSLN(double **abd, int ordr, int ofdg, double *b, int rhs);
extern "C" void BLCKTRI(int nblck,double (*a)[2], double (*b)[2], double (*c)[2], double (*d)[2]);
extern "C" void BLCKTRI2(int nblck,double (*a)[2], double (*b)[2], double (*c)[2], double (*d)[2], double (*e)[2]);
extern "C" int recur(int n,int ipoly, double al, double be, double *a, double *b);
extern "C" int radau(int n,double *alpha,double *beta, double end,double *zero,double *weight,double *e, double *a, double *b);
extern "C" int gauss(int n, const double *alpha,const double *beta, double eps, double *zero, double *weight, double *e);

PROTOCCALLSFSUB6(DGETRF,dgetrf,INT,INT,DOUBLEV,INT,INTV,PINT)
#define DGETRF(M,N,A,LDA,IPIV,INFO) CCALLSFSUB6(DGETRF,dgetrf,INT,INT,DOUBLEV,INT,INTV,PINT,M,N,A,LDA,IPIV,INFO)

PROTOCCALLSFSUB9(DGETRS,dgetrs,STRING,INT,INT,DOUBLEV,INT,INTV,DOUBLEV,INT,PINT)
#define DGETRS(trans,n,nrhs,a,lda,ipiv,b,ldb,info) CCALLSFSUB9(DGETRS,dgetrs,STRING,INT,INT,DOUBLEV,INT,INTV,DOUBLEV,INT,PINT,trans,n,nrhs,a,lda,ipiv,b,ldb,info)

PROTOCCALLSFSUB6(DPBTRF,dpbtrf,STRING,INT,INT,DOUBLEV,INT,PINT)
#define DPBTRF(UPLO,N,KD,AB,LDAB,INFO) CCALLSFSUB6(DPBTRF,dpbtrf,STRING,INT,INT,DOUBLEV,INT,PINT,UPLO,N,KD,AB,LDAB,INFO)

PROTOCCALLSFSUB9(DPBTRS,dpbtrs,STRING,INT,INT,INT,DOUBLEV,INT,DOUBLEV,INT,PINT)
#define DPBTRS(UPLO,N,KD,NRHS,AB,LDAB,B,LDB,INFO) CCALLSFSUB9(DPBTRS,dpbtrs,STRING,INT,INT,INT,DOUBLEV,INT,DOUBLEV,INT,PINT,UPLO,N,KD,NRHS,AB,LDAB,B,LDB,INFO)

PROTOCCALLSFSUB7(DPBCO,dpbco,DOUBLEV,INT,INT,INT,PDOUBLE,DOUBLEV,PINT)
#define DPBCO(ABD,LDA,N,M,RCOND,Z,INFO) CCALLSFSUB7(DPBCO,dpbco,DOUBLEV,INT,INT,INT,PDOUBLE,DOUBLEV,PINT,ABD,LDA,N,M,RCOND,Z,INFO)

PROTOCCALLSFSUB5(DPBSL,dpbsl,DOUBLEV,INT,INT,INT,DOUBLEV)
#define DPBSL(ABD,LDA,N,M,B) CCALLSFSUB5(DPBSL,dpbsl,DOUBLEV,INT,INT,INT,DOUBLEV,ABD,LDA,N,M,B)

PROTOCCALLSFSUB6(DPOCO,dpoco,DOUBLEV,INT,INT,PDOUBLE,DOUBLEV,PINT)
#define DPOCO(ABD,LDA,N,RCOND,Z,INFO) CCALLSFSUB6(DPOCO,dpoco,DOUBLEV,INT,INT,PDOUBLE,DOUBLEV,PINT,ABD,LDA,N,RCOND,Z,INFO)

PROTOCCALLSFSUB4(DPOSL,dposl,DOUBLEV,INT,INT,DOUBLEV)
#define DPOSL(ABD,LDA,N,B) CCALLSFSUB4(DPOSL,dposl,DOUBLEV,INT,INT,DOUBLEV,ABD,LDA,N,B)

PROTOCCALLSFSUB13(DSICS,dsics,INT,INT,INTV,INTV,DOUBLEV,INT,PINT,INTV,INTV,DOUBLEV,DOUBLEV,DOUBLEV,PINT)
#define DSICS(N,NELT,IA,JA,A,ISYM,NEL,IEL,JEL,EL,D,R,IWARN) CCALLSFSUB13(DSICS,dsics,INT,INT,INTV,INTV,DOUBLEV,INT,PINT,INTV,INTV,DOUBLEV,DOUBLEV,DOUBLEV,PINT,N,NELT,IA,JA,A,ISYM,NEL,IEL,JEL,EL,D,R,IWARN)

PROTOCCALLSFSUB8(SLLTI2,sllti2,INT,DOUBLEV,DOUBLEV,INT,INTV,INTV,DOUBLEV,DOUBLEV)
#define SLLTI2( N, B, X, NEL, IEL, JEL, EL, DINV ) CCALLSFSUB8(SLLTI2,sllti2,INT,DOUBLEV,DOUBLEV,INT,INTV,INTV,DOUBLEV,DOUBLEV,N, B, X, NEL, IEL, JEL, EL, DINV)

PROTOCCALLSFSUB11(DGELS,dgels,STRING,INT,INT,INT,DOUBLEV,INT,DOUBLEV,INT,DOUBLEV,INT,PINT)
#define DGELS(trans,m,n,nrhs,a,lda,b,ldb,work,lwork,info) CCALLSFSUB11(DGELS,dgels,STRING,INT,INT,INT,DOUBLEV,INT,DOUBLEV,INT,DOUBLEV,INT,PINT,trans,m,n,nrhs,a,lda,b,ldb,work,lwork,info)

PROTOCCALLSFSUB14(DGEEV,dgeev,STRING,STRING,INT,DOUBLEV,INT,DOUBLEV,DOUBLEV,DOUBLEV,INT,DOUBLEV,INT,DOUBLEV,INT,PINT)
#define DGEEV(JOBVL,JOBVR,N,A,LDA,WR,WI,VL,LDVL,VR,LDVR,WORK,LWORK,INFO) CCALLSFSUB14(DGEEV,dgeev,STRING,STRING,INT,DOUBLEV,INT,DOUBLEV,DOUBLEV,DOUBLEV,INT,DOUBLEV,INT,DOUBLEV,INT,PINT,JOBVL, JOBVR, N, A, LDA, WR, WI, VL, LDVL, VR, LDVR, WORK, LWORK, INFO)

#if (FLT == double)
#define GETRF DGETRF
#define GETRS DGETRS
#define PBTRF DPBTRF
#define PBTRS DPBTRS
#define EPSILON DBL_EPSILON
#else
#define GETRF SGETRF
#define GETRS SGETRS
#define PBTRF SPBTRF
#define PBTRS SPBTRS
#define EPSILON FLT_EPSILON
#endif

