#! /bin/csh

cp -f mesh.h ~/Codes/include
cp -f boundary.h ~/Codes/include
cp -f r_mesh.h ~/Codes/include
cp -f rboundary.h ~/Codes/include
#cd build/intermediates/mblock.build/Objects/ppc/
cd build/mesh.build/mblock.build/Objects-normal/ppc
libtool -o libmesh.a boundary.o coarsen.o collapse.o connect.o copy.o findmatch.o in_mesh.o insert.o out_mesh.o r_length.o r_mesh.o rboundary.o rebay.o setup.o swap.o tprims.o triangulate.o yaber.o
mv -f libmesh.a ~/Codes/lib

